# frozen_string_literal: true

require "pathname"
require "yaml"

module RuboCop
  module Neeto
    # `FleetTodo` is the per-app persistence layer that records pre-existing
    # bypasses of canonical Neeto nano APIs (e.g. raw `Faraday.post` calls that
    # should go through `NeetoWebhooksEngine::DeliverService`).
    #
    # Each entry is keyed by `(cop_name, file)` and stores an expected count of
    # matches in that file. Counts (rather than line numbers) are robust to
    # unrelated edits that would otherwise shift lines and create spurious
    # entries.
    #
    # File schema:
    #
    #     Neeto/WebhooksBypass:
    #       files:
    #         app/services/integrations/whatsapp/messages/send_service.rb: 1
    #         app/services/ai_assist/kb_validation_probe.rb: 1
    #
    # Semantics:
    #
    # * On a normal `rubocop` run, each cop calls `observe!` for every match it
    #   finds. `listed?` returns true while the per-file observation count is
    #   below the recorded ceiling — those matches are silently accepted.
    # * Matches beyond the ceiling become real offenses (new bypass).
    # * After a run, `stale_entries` reports files whose observed count fell
    #   below the recorded ceiling (a bypass got fixed but the entry is still
    #   on file). A separate task fails CI on stale entries to force the file
    #   to ratchet down.
    # * In record mode (`NEETO_FLEET_RECORD=1`), the cop suppresses offenses
    #   and `dump_recording!` rewrites the file from observed counts.
    #
    class FleetTodo
      HEADER = <<~YAML
        # This file lists pre-existing bypasses of canonical Neeto nano APIs
        # that have been grandfathered into this app. Counts are per-file.
        #
        # CI fails if a file has MORE matches than listed (new bypass) or
        # FEWER matches than listed (stale entry — the bypass was fixed, so
        # the entry should be removed).
        #
        # Regenerate with:
        #
        #   NEETO_FLEET_RECORD=1 bundle exec rubocop --only Neeto/WebhooksBypass
        #
        # Do not edit this file by hand to make CI green. Fix the bypass and
        # re-run the command above to prune the entry.
      YAML

      class << self
        def for(project_root)
          @instances ||= {}
          key = canonicalize(project_root).to_s
          @instances[key] ||= new(project_root)
        end

        def reset!
          @instances = nil
        end

        # Resolves symlinks so that paths that arrive via different routes
        # (e.g. `/var/folders/x` vs `/private/var/folders/x` on macOS) hash to
        # the same bucket. Falls back gracefully when the path or its parent
        # does not exist (specs often pass synthetic paths).
        def canonicalize(path)
          pathname = Pathname.new(path).expand_path
          if pathname.exist?
            pathname.realpath
          elsif pathname.dirname.exist?
            pathname.dirname.realpath.join(pathname.basename)
          else
            pathname
          end
        end
      end

      attr_reader :path, :project_root

      def initialize(project_root)
        @project_root = self.class.canonicalize(project_root)
        @path = @project_root.join("fleet_todo.yml")
        @old_entries = load_old_entries
        @observed_counts = Hash.new { |h, cop| h[cop] = Hash.new(0) }
      end

      def observe!(cop_name, file)
        @observed_counts[cop_name][relative(file)] += 1
      end

      def listed?(cop_name, file, occurrence_index)
        expected = old_count(cop_name, relative(file))
        occurrence_index < expected
      end

      def violations_over_limit
        report = {}
        @observed_counts.each do |cop, files|
          over = files.each_with_object({}) do |(file, count), acc|
            expected = old_count(cop, file)
            acc[file] = { observed: count, allowed: expected } if count > expected
          end
          report[cop] = over unless over.empty?
        end
        report
      end

      def stale_entries
        report = {}
        @old_entries.each do |cop, payload|
          stale = payload.fetch("files", {}).each_with_object({}) do |(file, expected), acc|
            observed = @observed_counts.dig(cop, file).to_i
            acc[file] = { observed:, allowed: expected } if observed < expected
          end
          report[cop] = stale unless stale.empty?
        end
        report
      end

      def dump_recording!
        merged = {}
        @observed_counts.sort.each do |cop, files|
          next if files.empty?

          merged[cop] = { "files" => files.sort.to_h }
        end
        write!(merged)
      end

      private

        def old_count(cop_name, relative_file)
          @old_entries.dig(cop_name, "files", relative_file).to_i
        end

        def relative(file)
          self.class.canonicalize(file).relative_path_from(@project_root).to_s
        end

        def load_old_entries
          return {} unless @path.exist?

          YAML.safe_load(@path.read) || {}
        end

        def write!(data)
          if data.empty?
            @path.delete if @path.exist?
            return
          end

          @path.open("w") do |f|
            f.write(HEADER)
            f.write(data.to_yaml)
          end
        end
    end
  end
end
